version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MONGODB_URL=${MONGODB_URL}
      - MONGODB_DB_NAME=${MONGODB_DB_NAME}
      - PINTEREST_USERNAME=${PINTEREST_USERNAME}
      - PINTEREST_PASSWORD=${PINTEREST_PASSWORD}
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge