version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY:-your_openai_api_key_here}
      - MONGODB_URI=${MONGODB_URI:-mongodb://localhost:27017/pinterest_scraper}
      - PINTEREST_USERNAME=${PINTEREST_USERNAME:-${PINTEREST_EMAIL:-your_pinterest_username}}
      - PINTEREST_PASSWORD=${PINTEREST_PASSWORD:-your_pinterest_password}
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge