version: '3.8'

services:
  frontend:
    build: ./frontend
    restart: unless-stopped
    networks:
      - app-network

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY:-your_openai_api_key_here}
      - MONGODB_URI=${MONGODB_URI:-mongodb://localhost:27017/pinterest_scraper}
    networks:
      - app-network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - app-network
    restart: unless-stopped



networks:
  app-network:
    driver: bridge
